### ISSUE TITLE
Create plot widget template

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/geppetto-hnn#52]
- [ ] Title
- [ ] Reset Changes Button
- [ ] Zoom Buttons
- [ ] Move Buttons
- [ ] Drag Button
- [ ] Save Button
- [ ] Axis Options Button
- [ ] Image/Plot 
- [ ] Window Buttons (maximize, minimize to tab, close)

**Comment by tarelli** [comment]
@afonsobspinto Let's update this

**Comment by afonsobspinto** [comment]
Closed because we are opting in for an external library instead.
