### ISSUE TITLE
Provide code/snippet to load model parameters

### ISSUE THREAD

**Issue by tarelli** [MetaCell/geppetto-hnn#84]
We need snippet to load netpyne model paramters or the original HNN ones

**Comment by salvadord** [comment]
to load original .param files: use hnn repo utils.py setCfgFromFile() func

**Comment by salvadord** [comment]
to load netpyne simConfig:
`sim.loadSimConfig(filename)`

**Comment by salvadord** [comment]
to load netpyne simConfig directly from json:
`with open('filename.json', 'r') as f: 
 cfg=json.load(f)

import specs
hnn_cfg = specs.simConfig(cfg)`
