### ISSUE TITLE
Unmatched Parameters 

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/geppetto-hnn#87]
Hello.
From comparing the dumped cfg (after using setCfgFromFile) with the cfg.py configuration I noticed that the following parameters don't match. I would guess that most of them are parameters that we don't need/want to export in HNN but I would prefer to have some confirmation.
```
{
  "hParams": {
    "clamp_resist": 0.001
  },
  "cvode_atol": 0.001,
  "rand123GlobalIndex": null,
  "createNEURONObj": true,
  "createPyStruct": true,
  "addSynMechs": true,
  "includeParamsLabel": true,
  "gatherOnlySimData": false,
  "compactConnFormat": false,
  "connRandomSecFromList": true,
  "saveCellSecs": true,
  "saveCellConns": true,
  "timing": true,
  "saveTiming": false,
  "printSynsAfterRule": false,
  "recordCellsSpikes": -1,
  "recordLFP": [],
  "saveLFPCells": false,
  "recordTime": true,
  "filename": "model_output",
  "timestampFilename": false,
  "saveMat": false,
  "saveCSV": false,
  "saveDpk": false,
  "saveHDF5": false,
  "saveDat": false,
  "backupCfgFile": [],
  "checkErrorsVerbose": false,
  "expmt_groups": "{default}",

}
```
Thanks

**Comment by salvadord** [comment]
All these are netpyne cfg parameters, that all netpyne models have.  Most of them should be in cfg.py under 'NetPyNE config parameters (not part of original HNN implementation)'.

The hnn-specific params are under 'HNN original config parameters (adapted to NetPyNE)'
